[package]
name = "nlc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive", "cargo"] }
tokio = { version = "1", features = ["full"] }
walkdir = "2"
sha2 = "0.10"